name: Deploy to Umbler
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Umbler
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Verificar se o repositório existe, senão clona
          if [ ! -d ".git" ]; then
            echo "Clonando repositório..."
            git clone https://github.com/marcelmaino/artiodonto-laravel.git .
          else
            echo "Atualizando repositório..."
            git pull origin main
          fi
          
          # Executar comandos Laravel se necessário
          # php artisan config:cache
          # php artisan route:cache
          # php artisan view:cache